const list = [
    {
        label: 'System',
        children: [
            { label: 'Plus' },
            { label: 'Minus' },
            { label: 'CirclePlus' },
            { label: 'Search' },
            { label: 'Female' },
            { label: 'Male' },
            { label: 'Aim' },
            { label: 'House' },
            { label: 'FullScreen' },
            { label: 'Loading' },
            { label: 'Link' },
            { label: 'Service' },
            { label: 'Pointer' },
            { label: 'Star' },
            { label: 'Notification' },
            { label: 'Connection' },
            { label: 'ChatDotRound' },
            { label: 'Setting' },
            { label: 'Clock' },
            { label: 'Position' },
            { label: 'Discount' },
            { label: 'Odometer' },
            { label: 'ChatSquare' },
            { label: 'ChatRound' },
            { label: 'ChatLineRound' },
            { label: 'ChatLineSquare' },
            { label: 'ChatDotSquare' },
            { label: 'View' },
            { label: 'Hide' },
            { label: 'Unlock' },
            { label: 'Lock' },
            { label: 'RefreshRight' },
            { label: 'RefreshLeft' },
            { label: 'Refresh' },
            { label: 'Bell' },
            { label: 'MuteNotification' },
            { label: 'User' },
            { label: 'Check' },
            { label: 'CircleCheck' },
            { label: 'Warning' },
            { label: 'CircleClose' },
            { label: 'Close' },
            { label: 'PieChart' },
            { label: 'More' },
            { label: 'Compass' },
            { label: 'Filter' },
            { label: 'Switch' },
            { label: 'Select' },
            { label: 'SemiSelect' },
            { label: 'CloseBold' },
            { label: 'EditPen' },
            { label: 'Edit' },
            { label: 'Message' },
            { label: 'MessageBox' },
            { label: 'TurnOff' },
            { label: 'Finished' },
            { label: 'Delete' },
            { label: 'Crop' },
            { label: 'SwitchButton' },
            { label: 'Operation' },
            { label: 'Open' },
            { label: 'Remove' },
            { label: 'ZoomOut' },
            { label: 'ZoomIn' },
            { label: 'InfoFilled' },
            { label: 'CircleCheckFilled' },
            { label: 'SuccessFilled' },
            { label: 'WarningFilled' },
            { label: 'CircleCloseFilled' },
            { label: 'QuestionFilled' },
            { label: 'WarnTriangleFilled' },
            { label: 'UserFilled' },
            { label: 'MoreFilled' },
            { label: 'Tools' },
            { label: 'HomeFilled' },
            { label: 'Menu' },
            { label: 'UploadFilled' },
            { label: 'Avatar' },
            { label: 'HelpFilled' },
            { label: 'Share' },
            { label: 'StarFilled' },
            { label: 'Comment' },
            { label: 'Histogram' },
            { label: 'Grid' },
            { label: 'Promotion' },
            { label: 'DeleteFilled' },
            { label: 'RemoveFilled' },
            { label: 'CirclePlusFilled' }
        ]
    },
    {
        label: 'Arrow',
        children: [
            { label: 'ArrowLeft' },
            { label: 'ArrowUp' },
            { label: 'ArrowRight' },
            { label: 'ArrowDown' },
            { label: 'ArrowLeftBold' },
            { label: 'ArrowUpBold' },
            { label: 'ArrowRightBold' },
            { label: 'ArrowDownBold' },
            { label: 'DArrowRight' },
            { label: 'DArrowLeft' },
            { label: 'Download' },
            { label: 'Upload' },
            { label: 'Top' },
            { label: 'Bottom' },
            { label: 'Back' },
            { label: 'Right' },
            { label: 'TopRight' },
            { label: 'TopLeft' },
            { label: 'BottomRight' },
            { label: 'BottomLeft' },
            { label: 'Sort' },
            { label: 'SortUp' },
            { label: 'SortDown' },
            { label: 'Rank' },
            { label: 'CaretLeft' },
            { label: 'CaretTop' },
            { label: 'CaretRight' },
            { label: 'CaretBottom' },
            { label: 'DCaret' },
            { label: 'Expand' },
            { label: 'Fold' }
        ]
    },
    {
        label: 'Document',
        children: [
            { label: 'DocumentAdd' },
            { label: 'Document' },
            { label: 'Notebook' },
            { label: 'Tickets' },
            { label: 'Memo' },
            { label: 'Collection' },
            { label: 'Postcard' },
            { label: 'ScaleToOriginal' },
            { label: 'SetUp' },
            { label: 'DocumentDelete' },
            { label: 'DocumentChecked' },
            { label: 'DataBoard' },
            { label: 'DataAnalysis' },
            { label: 'CopyDocument' },
            { label: 'FolderChecked' },
            { label: 'Files' },
            { label: 'Folder' },
            { label: 'FolderDelete' },
            { label: 'FolderRemove' },
            { label: 'FolderOpened' },
            { label: 'DocumentCopy' },
            { label: 'DocumentRemove' },
            { label: 'FolderAdd' },
            { label: 'FirstAidKit' },
            { label: 'Reading' },
            { label: 'DataLine' },
            { label: 'Management' },
            { label: 'Checked' },
            { label: 'Ticket' },
            { label: 'Failed' },
            { label: 'TrendCharts' },
            { label: 'List' }
        ]
    },
    {
        label: 'Media',
        children: [
            { label: 'Microphone' },
            { label: 'Mute' },
            { label: 'Mic' },
            { label: 'VideoPause' },
            { label: 'VideoCamera' },
            { label: 'VideoPlay' },
            { label: 'Headset' },
            { label: 'Monitor' },
            { label: 'Film' },
            { label: 'Camera' },
            { label: 'Picture' },
            { label: 'PictureRounded' },
            { label: 'Iphone' },
            { label: 'Cellphone' },
            { label: 'VideoCameraFilled' },
            { label: 'PictureFilled' },
            { label: 'Platform' },
            { label: 'CameraFilled' },
            { label: 'BellFilled' }
        ]
    },
    {
        label: 'Traffic',
        children: [
            { label: 'Location' },
            { label: 'LocationInformation' },
            { label: 'DeleteLocation' },
            { label: 'Coordinate' },
            { label: 'Bicycle' },
            { label: 'OfficeBuilding' },
            { label: 'School' },
            { label: 'Guide' },
            { label: 'AddLocation' },
            { label: 'MapLocation' },
            { label: 'Place' },
            { label: 'LocationFilled' },
            { label: 'Van' },
        ]
    },
    {
        label: 'Food',
        children: [
            { label: 'Watermelon' },
            { label: 'Pear' },
            { label: 'NoSmoking' },
            { label: 'Smoking' },
            { label: 'Mug' },
            { label: 'GobletSquareFull' },
            { label: 'GobletFull' },
            { label: 'KnifeFork' },
            { label: 'Sugar' },
            { label: 'Bowl' },
            { label: 'MilkTea' },
            { label: 'Lollipop' },
            { label: 'Coffee' },
            { label: 'Chicken' },
            { label: 'Dish' },
            { label: 'IceTea' },
            { label: 'ColdDrink' },
            { label: 'CoffeeCup' },
            { label: 'DishDot' },
            { label: 'IceDrink' },
            { label: 'IceCream' },
            { label: 'Dessert' },
            { label: 'IceCreamSquare' },
            { label: 'ForkSpoon' },
            { label: 'IceCreamRound' },
            { label: 'Food' },
            { label: 'HotWater' },
            { label: 'Grape' },
            { label: 'Fries' },
            { label: 'Apple' },
            { label: 'Burger' },
            { label: 'Goblet' },
            { label: 'GobletSquare' },
            { label: 'Orange' },
            { label: 'Cherry' },
        ]
    },
    {
        label: 'Items',
        children: [
            { label: 'Printer' },
            { label: 'Calendar' },
            { label: 'CreditCard' },
            { label: 'Box' },
            { label: 'Money' },
            { label: 'Refrigerator' },
            { label: 'Cpu' },
            { label: 'Football' },
            { label: 'Brush' },
            { label: 'Suitcase' },
            { label: 'SuitcaseLine' },
            { label: 'Umbrella' },
            { label: 'AlarmClock' },
            { label: 'Medal' },
            { label: 'GoldMedal' },
            { label: 'Present' },
            { label: 'Mouse' },
            { label: 'Watch' },
            { label: 'QuartzWatch' },
            { label: 'Magnet' },
            { label: 'Help' },
            { label: 'Soccer' },
            { label: 'ToiletPaper' },
            { label: 'ReadingLamp' },
            { label: 'Paperclip' },
            { label: 'MagicStick' },
            { label: 'Basketball' },
            { label: 'Baseball' },
            { label: 'Coin' },
            { label: 'Goods' },
            { label: 'Sell' },
            { label: 'SoldOut' },
            { label: 'Key' },
            { label: 'ShoppingCart' },
            { label: 'ShoppingCartFull' },
            { label: 'ShoppingTrolley' },
            { label: 'Phone' },
            { label: 'Scissor' },
            { label: 'Handbag' },
            { label: 'ShoppingBag' },
            { label: 'Trophy' },
            { label: 'TrophyBase' },
            { label: 'Stopwatch' },
            { label: 'Timer' },
            { label: 'CollectionTag' },
            { label: 'TakeawayBox' },
            { label: 'PriceTag' },
            { label: 'Wallet' },
            { label: 'Opportunity' },
            { label: 'PhoneFilled' },
            { label: 'WalletFilled' },
            { label: 'GoodsFilled' },
            { label: 'Flag' },
            { label: 'BrushFilled' },
            { label: 'Briefcase' },
            { label: 'Stamp' }
        ]
    },
    {
        label: 'Weather',
        children: [
            { label: 'Sunrise' },
            { label: 'Sunny' },
            { label: 'Ship' },
            { label: 'MostlyCloudy' },
            { label: 'PartlyCloudy' },
            { label: 'Sunset' },
            { label: 'Drizzling' },
            { label: 'Pouring' },
            { label: 'Cloudy' },
            { label: 'Moon' },
            { label: 'MoonNight' },
            { label: 'Lightning' }
        ]
    },
    {
        label: 'Other',
        children: [
            { label: 'ChromeFilled' },
            { label: 'Eleme' },
            { label: 'ElemeFilled' },
            { label: 'ElementPlus' },
            { label: 'Shop' },
            { label: 'SwitchFilled' },
            { label: 'WindPower' }
        ]
    },
]
export default list; 